// Centralized API client generated by Jonnah
export const API_BASE = '/api-gkii';

export async function apiRequest(path, options = {}) {
  const res = await fetch(, {
    headers: { 'Content-Type': 'application/json' },
    ...options
  });
  if (!res.ok) {
    throw new Error('API error: ' + res.status);
  }
  return res.json();
}
