<?php
// Basic CRUD endpoint generated by Jonnah
require_once '../config/database.php';

header('Content-Type: application/json');

 = ['REQUEST_METHOD'];

if( === 'GET'){
  echo json_encode(['message'=>'list jemaat']);
}

if( === 'POST'){
  echo json_encode(['message'=>'create jemaat']);
}

?>
